
CondaError: Run 'conda init' before 'conda activate'

Traceback (most recent call last):
  File "/u/home/wyou/.conda/envs/ADML/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/vol/miltank/users/wyou/Documents/nnUNet/nnunetv2/run/run_training.py", line 267, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/vol/miltank/users/wyou/Documents/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/vol/miltank/users/wyou/Documents/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1259, in perform_actual_validation
    proceed = not check_workers_alive_and_busy(segmentation_export_pool, worker_list, results,
  File "/vol/miltank/users/wyou/Documents/nnUNet/nnunetv2/utilities/file_path_utilities.py", line 103, in check_workers_alive_and_busy
    raise RuntimeError('Some background workers are no longer alive')
RuntimeError: Some background workers are no longer alive
slurmstepd: error: Detected 1 oom_kill event in StepId=14477.batch. Some of the step tasks have been OOM Killed.
